//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboCotacaoBradesco.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Libs\\LoginPagesChrome\\")]
        public string CaminhoDriverChrome {
            get {
                return ((string)(this["CaminhoDriverChrome"]));
            }
            set {
                this["CaminhoDriverChrome"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"user id=ADM;pwd=ADMUSR;Application Name=BRADESCO_SEGUROS;data source=TMKT-ZL-DB26;persist security info=False;connection reset=false;Pooling=true;Connection Lifetime=1800;initial catalog=BRADESCO_SEGUROS;min pool size=1;max pool size=999;Connect Timeout=1800")]
        public string AcessoBanco {
            get {
                return ((string)(this["AcessoBanco"]));
            }
        }
    }
}
